[package]
name = "is-google"
description = ""
version = "0.1.0"
license = "MIT"
readme = "README.md"
authors = ["Daniel Lockyer <daniel@daniellockyer.com>"]
repository = "https://github.com/neosilky/is-google"
homepage = "https://github.com/neosilky/is-google"

[dependencies]
dns-lookup = "1.0.1"
